import type { Metadata } from "next";
import { Martel_Sans, Cormorant_Infant, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

// Load Cormorant Infant with only weight 600
const cormorantInfant = Cormorant_Infant({
  variable: "--font-cormorant-infant",
  weight: "600",
  subsets: ["latin"],
  style: ["italic"],
});

// Load Martel Sans with multiple weights
const martelSans = Martel_Sans({
  variable: "--font-martel-sans",
  weight: ["400", "600"],
  subsets: ["latin"],
});

// Load Roboto
const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Psychoanalyst - Haifaa Bitar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorantInfant.variable} ${roboto.variable} antialiased bg-bg-color text-primary font-text`}
      >
        <Navbar />
        <main className="space-y-60 lg:space-y-72 xl:space-y-80 mb-60 lg:mb-72 xl:mb-80 ">

        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
